services:
  db:
    image: mariadb:latest
    container_name: db
    environment:
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_DATABASE=docker_db
      - DATABASE_HOST=mariadb 
      - DATABASE_PORT=3306 
      - DATABASE_USER='root'
      - DATABASE_PASSWORD='pass'
      - DATABASE_NAME='docker_db'
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "-uroot", "-ppass", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  app:
    build: 
      context: .
    container_name: my-nest-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge