services:
  app:
    build: 
      context: .
    container_name: my-nest-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mariadb:latest
    container_name: db
    environment:
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_DATABASE=docker_db
      - DATABASE_HOST=mariadb 
      - DATABASE_PORT=3306 
      - DATABASE_USER='root'
      - DATABASE_PASSWORD='pass'
      - DATABASE_NAME='docker_db'
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge